---
format: typst
---
# Findings

## Profile

- `fiscal_year` on `profile` table represents the fiscal year of release date
- `profile` rows were queried by release dates within fiscal years 2024 and 2025
- `doc_num` is not distinct
  - Some duplicate `doc_num` due to separate periods, but some have same `admit_date` and different `release_date`
  - 10 rows (5 people) have same `admit_date` with different `release_date`
  - This causes a many-to-many join when attempting to add to `sentence`
  - Some duplicate `release_date` are in different months
  - All duplicate `release_date` are in same fiscal year

## Sentences

- Not all `fiscal_year` match between joined `profile` and `sentence`
- Some sentence dates appear corrupted
- `js_date` is often (~25% of those in this set) over 1 year away from `admit_date`

## Alias

- Lots of aliases don't link to a profile and vice versa.


# Conclusions

- Prison Admissions
  - Only captures admissions if the person was eventually released in FY2024-2025
  - Need to query all admissions within FY2024-2025
- Prison Sentences
  - Only captures sentences of those people released in FY2024-2025
  - Need to query all sentences within FY2024-2025
  - Some dates are corrupted in received data
    - This can be cleaned up on our end
- Population
  - Profile table only covers those released within FY2024-2025
  - Need to query all profiles where there is no release date, release date is in the future (if possible in the database), or where release date is within FY2024-2025
- County Comparison
  - Since sentencing county comes from sentencing table the same query range issue applies
- Prison Releases
  - This is the only metric correctly captured
  - Data was specifically queried by release dates
  - Duplicate `doc_nums` means some individuals are counted multiple times
